version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=central_db
    ports:
      - "4003:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  estudiantes:
    build:
      context: ./estudiantes
    container_name: estudiantes
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "4004:4004"

  inscripciones:
    build:
      context: ./inscripciones
    container_name: inscripciones
    restart: on-failure
    depends_on:
      - db
    ports:
      - "4005:4005"
